spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.config.import-check.enabled=false
spring.cloud.gateway.server.webflux.routes[0].id=authService
spring.cloud.gateway.server.webflux.routes[0].uri=lb://authService
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/authService/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[1].id=masterService
spring.cloud.gateway.server.webflux.routes[1].uri=lb://masterService
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/masterService/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[2].id=msaService
spring.cloud.gateway.server.webflux.routes[2].uri=lb://msa-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/msaService/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1


spring.cloud.gateway.server.webflux.routes[3].id=garmentService
spring.cloud.gateway.server.webflux.routes[3].uri=lb://garmentService
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/garmentService/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[4].id=assessmentService
spring.cloud.gateway.server.webflux.routes[4].uri=lb://assessmentService
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/assessmentService/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=StripPrefix=1


#jwt.secret=${JWT_SECRET}
jwt.secret=JHtKV1RfU0VDUkVUOlRYbE1iMk5oYkVwM2RGTmxZM0psZEV0bGVWOHlNREkyWDFObFkzVnlaVjg0WmtzeU9YaE1iVkUzZGxJemNGUTJ9

gateway.open-endpoints=/authService/auth/v1/login,/authService/auth/v1/refresh-token,/authService/auth/v1/captcha