spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.config.import-check.enabled=false
spring.cloud.gateway.server.webflux.routes[0].id=authService
spring.cloud.gateway.server.webflux.routes[0].uri=lb://authService
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/authService/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[1].id=masterService
spring.cloud.gateway.server.webflux.routes[1].uri=lb://masterService
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/masterService/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1


jwt.secret=${JWT_SECRET}


gateway.open-endpoints=/authService/auth/v1/login,/authService/auth/v1/refresh-token,/authService/auth/v1/captcha