spring.application.name=authService

# ===========================
# Eureka Client Configuration
# ===========================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}

server.port=0
server.address=0.0.0.0

# =================================
# PostgreSQL database configuration
# =================================
spring.datasource.url=jdbc:postgresql://localhost:5434/msadb?currentSchema=security
spring.datasource.username=${DB_USER:karthik}
spring.datasource.password=${DB_PASSWORD:optipace123}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================
# Hibernate settings
# ===================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.default_schema=security

jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh.expiration=86400000